In [1]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
from matplotlib.colors import Normalize, LinearSegmentedColormap
from matplotlib.colorbar import ColorbarBase
from matplotlib.gridspec import GridSpec, GridSpecFromSubplotSpec
from matplotlib.cm import ScalarMappable
import pandas as pd

In [6]:
power_emm           = pd.read_csv("pilot2/only_subjects/r_stuff/power_emm.csv")
coherence_emm       = pd.read_csv("pilot2/only_subjects/r_stuff/coherence_emm.csv")
power_contrasts     = pd.read_csv("pilot2/only_subjects/r_stuff/power_contrasts.csv")
coherence_contrasts = pd.read_csv("pilot2/only_subjects/r_stuff/coherence_contrasts.csv")
granger_emm           = pd.read_csv("pilot2/only_subjects/r_stuff/granger_emm.csv")
granger_contrasts     = pd.read_csv("pilot2/only_subjects/r_stuff/granger_contrasts.csv")

In [12]:
power_emm_cups           = pd.read_csv("pilot2/cups_phase4/r_stuff/no_pref/power_emm.csv")
coherence_emm_cups       = pd.read_csv("pilot2/cups_phase4/r_stuff/no_pref/coherence_emm.csv")
power_contrasts_cups     = pd.read_csv("pilot2/cups_phase4/r_stuff/no_pref/power_contrasts.csv")
coherence_contrasts_cups = pd.read_csv("pilot2/cups_phase4/r_stuff/no_pref/coherence_contrasts.csv")
granger_emm_cups           = pd.read_csv("pilot2/cups_phase4/r_stuff/no_pref/granger_emm.csv")
granger_contrasts_cups     = pd.read_csv("pilot2/cups_phase4/r_stuff/no_pref/granger_contrasts.csv")

In [14]:
power_emm_habit           = pd.read_csv("pilot2/habit_dishabit_phase1/r_stuff/cage_v_nov_power_emm.csv")
coherence_emm_habit       = pd.read_csv("pilot2/habit_dishabit_phase1/r_stuff/cage_v_nov_coherence_emm.csv")
power_contrasts_habit     = pd.read_csv("pilot2/habit_dishabit_phase1/r_stuff/cage_v_nov_power_contrasts.csv")
coherence_contrasts_habit = pd.read_csv("pilot2/habit_dishabit_phase1/r_stuff/cage_v_nov_coherence_contrasts.csv")
granger_emm_habit           = pd.read_csv("pilot2/habit_dishabit_phase1/r_stuff/cage_v_nov_granger_emm.csv")
granger_contrasts_habit     = pd.read_csv("pilot2/habit_dishabit_phase1/r_stuff/cage_v_nov_granger_contrasts.csv")

In [17]:
power_emm.columns

Index(['agent', 'band', 'emmean', 'SE', 'df', 'lower.CL', 'upper.CL',
       'region'],
      dtype='object')

In [30]:
power_merged = pd.merge(power_contrasts, power_contrasts_cups, on=['region', 'band', 'contrast', 'plot_type'], suffixes=('_freely_moving', '_cups'))
power_merged_sig = power_merged[(power_merged['sig_cups'].isin(['.', '*', '**', '***'])) & (power_merged['sig_freely_moving'].isin(['.', '*', '**', '***']))]
power_merged_sig[np.sign(power_merged_sig['t.ratio_cups']) == np.sign(power_merged_sig['t.ratio_freely_moving'])]

,region,model_formula_freely_moving,plot_type,contrast,band,estimate_freely_moving,SE_freely_moving,df_freely_moving,t.ratio_freely_moving,p.value_freely_moving,p.value.adjusted_freely_moving,sig_freely_moving,model_formula_cups,estimate_cups,SE_cups,df_cups,t.ratio_cups,p.value_cups,p.value.adjusted_cups,sig_cups
46,BLA,value ~ band * agent + velocity_mouse1 + (1 | ...,interaction,cagemate - novel,Delta,10.238423,2.83333,4472.756724,3.613566,0.000305,0.00458,**,value ~ band * agent + band + band * event_len...,14.056399,3.641797,2422.002774,3.859743,0.000116,0.001048,**

In [34]:
power_merged_cage_v_nov = pd.merge(power_merged, power_contrasts_habit, on=['region', 'band', 'contrast', 'plot_type'], suffixes=('', '_habit'))
power_merged_cage_v_nov

,region,model_formula_freely_moving,plot_type,contrast,band,estimate_freely_moving,SE_freely_moving,df_freely_moving,t.ratio_freely_moving,p.value_freely_moving,...,p.value.adjusted_cups,sig_cups,model_formula,estimate,SE,df,t.ratio,p.value,p.value.adjusted,sig
0,mPFC,value ~ band * agent + velocity_mouse1 + (1 | ...,interaction,cagemate - novel,Delta,-3.381798,2.958594,4628.100659,-1.143042,0.253080,...,1.010818e-07,***,value ~ band * condition + velocity_mouse1 + e...,-55.573964,13.552700,14.697976,-4.100582,0.000983,0.024576,*
1,mPFC,value ~ band * agent + velocity_mouse1 + (1 | ...,interaction,cagemate - novel,Theta,4.018886,2.958594,4628.100659,1.358377,0.174410,...,3.621660e-01,NaN,value ~ band * condition + velocity_mouse1 + e...,-0.055693,13.552700,14.697976,-0.004109,0.996776,0.999086,NaN
2,mPFC,value ~ band * agent + velocity_mouse1 + (1 | ...,interaction,cagemate - novel,Beta,0.553071,2.958594,4628.100659,0.186937,0.851718,...,6.123264e-01,NaN,value ~ band * condition + velocity_mouse1 + e...,2.522150,13.552700,14.697976,0.186099,0.854911,0.999086,NaN
3,mPFC,value ~ band * agent + velocity_mouse1 + (1 | ...,interaction,cagemate - novel,Low gamma,-4.765355,2.958594,4628.100659,-1.610682,0.107317,...,2.987643e-01,NaN,value ~ band * condition + velocity_mouse1 + e...,-3.822486,13.552700,14.697976,-0.282046,0.781841,0.977301,NaN
4,mPFC,value ~ band * agent + velocity_mouse1 + (1 | ...,interaction,cagemate - novel,High gamma,-5.378414,2.958594,4628.100659,-1.817895,0.069145,...,6.123264e-01,NaN,value ~ band * condition + velocity_mouse1 + e...,-9.334307,13.552700,14.697976,-0.688741,0.501714,0.747993,NaN
5,MD,value ~ band * agent + velocity_mouse1 + (1 | ...,interaction,cagemate - novel,Delta,-0.471825,2.995131,4643.398064,-0.157531,0.874833,...,7.039818e-02,.,value ~ band * condition + velocity_mouse1 + e...,14.645464,9.920587,11.525154,1.476270,0.166665,0.592838,NaN
6,MD,value ~ band * agent + velocity_mouse1 + (1 | ...,interaction,cagemate - novel,Theta,3.854998,2.995131,4643.398064,1.287088,0.198128,...,6.713281e-01,NaN,value ~ band * condition + velocity_mouse1 + e...,-16.925710,9.920587,11.525154,-1.706120,0.114759,0.573794,NaN
7,MD,value ~ band * agent + velocity_mouse1 + (1 | ...,interaction,cagemate - novel,Beta,0.551748,2.995131,4643.398064,0.184215,0.853853,...,6.123264e-01,NaN,value ~ band * condition + velocity_mouse1 + e...,-22.300746,9.920587,11.525154,-2.247926,0.045019,0.281369,NaN
8,MD,value ~ band * agent + velocity_mouse1 + (1 | ...,interaction,cagemate - novel,Low gamma,-0.710481,2.995131,4643.398064,-0.237212,0.812503,...,4.487140e-01,NaN,value ~ band * condition + velocity_mouse1 + e...,-23.958672,9.920587,11.525154,-2.415046,0.033377,0.278140,NaN
9,MD,value ~ band * agent + velocity_mouse1 + (1 | ...,interaction,cagemate - novel,High gamma,-0.743307,2.995131,4643.398064,-0.248172,0.804012,...,1.085901e-01,NaN,value ~ band * condition + velocity_mouse1 + e...,-25.161865,9.920587,11.525154,-2.536328,0.026812,0.278140,NaN

In [ ]:
power_merged_cage_v_nov_sig = power_merged_cage_v_nov[(power_merged_cage_v_nov['sig_cups'].isin(['.', '*', '**', '***'])) & (power_merged_cage_v_nov['sig_freely_moving'].isin(['.', '*', '**', '***'])) & (power_merged_cage_v_nov['sig'].isin(['.', '*', '**', '***']))]
power_merged_cage_v_nov_sig[(power_merged_cage_v_nov_sig['t.ratio_cups'] * 
                            power_merged_cage_v_nov_sig['t.ratio_freely_moving'] *
                            power_merged_cage_v_nov_sig['t.ratio']) > 0]

Empty DataFrame
Columns: [region, model_formula_freely_moving, plot_type, contrast, band, estimate_freely_moving, SE_freely_moving, df_freely_moving, t.ratio_freely_moving, p.value_freely_moving, p.value.adjusted_freely_moving, sig_freely_moving, model_formula_cups, estimate_cups, SE_cups, df_cups, t.ratio_cups, p.value_cups, p.value.adjusted_cups, sig_cups, model_formula, estimate, SE, df, t.ratio, p.value, p.value.adjusted, sig]
Index: []

[0 rows x 28 columns]

In [38]:
coherence_merged = pd.merge(coherence_contrasts, coherence_contrasts_cups, on=['region', 'band', 'contrast', 'plot_type'], suffixes=('_freely_moving', '_cups'))
coherence_merged_sig = coherence_merged[(coherence_merged['sig_cups'].isin(['.', '*', '**', '***'])) & (coherence_merged['sig_freely_moving'].isin(['.', '*', '**', '***']))]
coherence_merged_sig[np.sign(coherence_merged_sig['t.ratio_cups']) == np.sign(coherence_merged_sig['t.ratio_freely_moving'])]

,region,model_formula_freely_moving,plot_type,contrast,band,estimate_freely_moving,SE_freely_moving,df_freely_moving,t.ratio_freely_moving,p.value_freely_moving,p.value.adjusted_freely_moving,sig_freely_moving,model_formula_cups,estimate_cups,SE_cups,df_cups,t.ratio_cups,p.value_cups,p.value.adjusted_cups,sig_cups
3,mPFC_BLA,value ~ band * agent + velocity_mouse1 + (1 | ...,interaction,cagemate - familiar,Theta,5.418432,1.551083,3618.997924,3.493321,0.000483,0.00515,**,value ~ band * agent + (1 | X),5.773531,1.859727,2036.440893,3.104505,0.001932,0.029287,*

In [40]:
coherence_merged_cage_v_nov = pd.merge(coherence_merged, coherence_contrasts_habit, on=['region', 'band', 'contrast', 'plot_type'], suffixes=('', '_habit'))
coherence_merged_cage_v_nov_sig = coherence_merged_cage_v_nov[(coherence_merged_cage_v_nov['sig_cups'].isin(['.', '*', '**', '***'])) & (coherence_merged_cage_v_nov['sig_freely_moving'].isin(['.', '*', '**', '***'])) & (coherence_merged_cage_v_nov['sig'].isin(['.', '*', '**', '***']))]
coherence_merged_cage_v_nov_sig[(coherence_merged_cage_v_nov_sig['t.ratio_cups'] * 
                            coherence_merged_cage_v_nov_sig['t.ratio_freely_moving'] *
                            coherence_merged_cage_v_nov_sig['t.ratio']) > 0]

Empty DataFrame
Columns: [region, model_formula_freely_moving, plot_type, contrast, band, estimate_freely_moving, SE_freely_moving, df_freely_moving, t.ratio_freely_moving, p.value_freely_moving, p.value.adjusted_freely_moving, sig_freely_moving, model_formula_cups, estimate_cups, SE_cups, df_cups, t.ratio_cups, p.value_cups, p.value.adjusted_cups, sig_cups, model_formula, estimate, SE, df, t.ratio, p.value, p.value.adjusted, sig]
Index: []

[0 rows x 28 columns]

In [42]:
granger_merged = pd.merge(granger_contrasts, granger_contrasts_cups, on=['region', 'band', 'contrast', 'plot_type'], suffixes=('_freely_moving', '_cups'))
granger_merged_sig = granger_merged[(granger_merged['sig_cups'].isin(['.', '*', '**', '***'])) & (granger_merged['sig_freely_moving'].isin(['.', '*', '**', '***']))]
granger_merged_sig[np.sign(granger_merged_sig['t.ratio_cups']) == np.sign(granger_merged_sig['t.ratio_freely_moving'])]

,region,model_formula_freely_moving,plot_type,contrast,band,estimate_freely_moving,SE_freely_moving,df_freely_moving,t.ratio_freely_moving,p.value_freely_moving,p.value.adjusted_freely_moving,sig_freely_moving,model_formula_cups,estimate_cups,SE_cups,df_cups,t.ratio_cups,p.value_cups,p.value.adjusted_cups,sig_cups
15,vHPC_to_NAc,value ~ band * agent + velocity_mouse1 + (1 | ...,interaction,cagemate - familiar,Delta,-9.395355,3.708779,3350.338851,-2.533274,0.011345,0.072935,.,value ~ band * agent + (1 | X),-27.353165,4.961258,1836.196428,-5.513353,4.019536e-08,0.000003,***

In [43]:
granger_merged_cage_v_nov = pd.merge(granger_merged, granger_contrasts_habit, on=['region', 'band', 'contrast', 'plot_type'], suffixes=('', '_habit'))
granger_merged_cage_v_nov_sig = granger_merged_cage_v_nov[(granger_merged_cage_v_nov['sig_cups'].isin(['.', '*', '**', '***'])) & (granger_merged_cage_v_nov['sig_freely_moving'].isin(['.', '*', '**', '***'])) & (granger_merged_cage_v_nov['sig'].isin(['.', '*', '**', '***']))]
granger_merged_cage_v_nov_sig[(granger_merged_cage_v_nov_sig['t.ratio_cups'] * 
                            granger_merged_cage_v_nov_sig['t.ratio_freely_moving'] *
                            granger_merged_cage_v_nov_sig['t.ratio']) > 0]

Empty DataFrame
Columns: [region, model_formula_freely_moving, plot_type, contrast, band, estimate_freely_moving, SE_freely_moving, df_freely_moving, t.ratio_freely_moving, p.value_freely_moving, p.value.adjusted_freely_moving, sig_freely_moving, model_formula_cups, estimate_cups, SE_cups, df_cups, t.ratio_cups, p.value_cups, p.value.adjusted_cups, sig_cups, model_formula, estimate, SE, df, t.ratio, p.value, p.value.adjusted, sig]
Index: []

[0 rows x 28 columns]